### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by csabakos** [opentracing-contrib/java-reactor#1]
Please publish `opentracing-reactor` to Maven Central so that it can be imported from other projects.

(In particular, I'm planning to add a Spring Boot starter for it in `java-spring-cloud`).

Thank you!

**Comment by jam01** [comment]
That sounds great. I'll look into it this weekend.

**Comment by csabakos** [comment]
Hi @jam01, just checking in. How is the progress on this one? Is there anything that I could help out with?

(This issue, along with the starter that I'm planning to add in `java-spring-cloud`, is needed to complete the [Spring WebFlux/WebClient tracing](https://github.com/opentracing-contrib/java-spring-web/pull/95) feature.)

**Comment by jam01** [comment]
Working on this, sorry for the delay...

**Comment by jam01** [comment]
Should be good

https://search.maven.org/artifact/io.opentracing.contrib/opentracing-reactor/0.0.2/jar

**Comment by csabakos** [comment]
Thank you @jam01, looks good!
