### ISSUE TITLE
subscribeOn supported?

### ISSUE THREAD

**Issue by atomictag** [opentracing-contrib/java-reactor#3]
Quick question: are traces propagated also in reactive chains where subscribeOn is used? I don't seem to get this to work properly and traces disappear when for example `.subscribeOn(Schedulers.elastic())` is used. Thanks in advance

**Comment by jam01** [comment]
This should work, yes. Are you using SpecialAgent or did you register the Hooks yourself? I'm thinking this may be the thread local scopes not being passed in the executors. 

If you manually registered the hooks then we'd also need to use TracedExecutors from  java-concurrent contrib project and register it with `Schedulers`. This may be something we could do within this library, just have to figure out how to do it in a way it doesn't interfere with SpecialAgent's instrumentation.

**Comment by atomictag** [comment]
Thank you. I think you are absolutely right - I followed your advice and I am getting closer to a fully working solutions. Using Jaeger here - with manual hooks registration.

Out of the box this is what happens:
```
...
// some span started active here
...
Mono.fromCallable(() -> {
    // here tracer.activeSpan() is null!!
    ...
}).doOnSubscribe(sub -> {
    // here tracer.activeSpan() is the expected one
    ...
}).subscribeOn(Schedulers.elastic())
```
Using `Schedulers.setExecutorServiceDecorator` with a suitable `io.opentracing.contrib.concurrent.TracedScheduledExecutorService` from https://github.com/opentracing-contrib/java-concurrent makes it work. 

Thanks for the hint!

**Comment by csabakos** [comment]
I recommend using the [starter from java-spring-cloud](https://github.com/opentracing-contrib/java-spring-cloud/blob/master/instrument-starters/opentracing-spring-cloud-reactor-starter/src/main/java/io/opentracing/contrib/spring/cloud/reactor/ReactorTracingAutoConfiguration.java). It does this for you: https://github.com/opentracing-contrib/java-spring-cloud/pull/208
