### ISSUE TITLE
Upgrade OpenTracing API to 0.32.0

### ISSUE THREAD

**Issue by pavolloffay** [opentracing-contrib/java-reactor#5]
@jam01 would you like to take this one?

**Comment by pavolloffay** [comment]
@jam01 any update on this? We would like to update to 0.32.0 in spring cloud

**Comment by jam01** [comment]
Hey Pavol. Sorry, this must've gotten lost in all the GitHub OT notifications I've been getting. But yes I can take this on, I'll have time this weekend if that works for you.

**Comment by pavolloffay** [comment]
Perfect, ping be back please.

**Comment by jam01** [comment]
@pavolloffay upgraded to 32. Let me know if you want to take a look at the changes, otherwise I'll release 0.1.0 later today

**Comment by pavolloffay** [comment]
thanks @jam01.
